name: Build and Deploy Hakyll Site

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cabal
        run: sudo apt-get update && sudo apt-get install -y cabal-install

      - name: Install GHC
        run: sudo apt-get update && sudo apt-get install -y ghc

      - name: Build Hakyll site
        run: |
          cabal update

          # Replace 'build' with the command to build your Hakyll site
          cabal run site build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
